

module.exports = function(){
 return {
		"ME":
		{
			"Mjólk (kg) 1":"mjolk_kg_1",
			"Mjólk (kg) 2":"mjolk_kg_2",
			"Mjólk (kg) 3":"mjolk_kg_3",
			"Fita (kg) 1":"fita_kg_1",
			"Fita (kg) 2":"fita_kg_2",
			"Fita (kg) 3":"fita_kg_3",
			"Prótein (kg) 1":"protein_kg_1",
			"Prótein (kg) 2":"protein_kg_2",
			"Prótein (kg) 3":"protein_kg_3",
			"Fita (%) 1":"fituhlutfall_1",
			"Fita (%) 2":"fituhlutfall_2",
			"Fita (%) 3":"fituhlutfall_3",
			"Prótein (%) 1":"proteinhlutfall_1",
			"Prótein (%) 2":"proteinhlutfall_2",
			"Prótein (%) 3":"proteinhlutfall_3",
			"Frjósemi 1":"frjosemi_1",
			"Frjósemi 2":"frjosemi_2",
			"Frjósemi 3":"frjosemi_3",
			"Frumutala 1":"frumutala_1",
			"Frumutala 2":"frumutala_2",
			"Frumutala 3":"frumutala_3"
		},
		"EK":
		{
			"Bandmál":"em_bandmal",
			"Bolur":"em_bolur",
			"Malir":"em_malir",
			"Fótstaða":"em_fotstada",
			"Júgurlag/júgurfesta":"em_jugur",
			"Spenalengd/spenalag":"em_spenar",
			"Mjaltir":"em_mjaltir",
			"Skap":"em_skap"
		},
		"NK":
		{
			"Boldýpt":"nm_boldypt",
			"Útlögur":"nm_utlogur",
			"Yfirlina":"nm_yfirlina",
			"Malabreidd":"nm_malabreidd",
			"Malahalli":"nm_malahallir",
			"Malabratti":"nm_malabratti",
			"Staða h. ekla hlið":"nm_fotstada_hlid",
			"Staða h. aftan":"nm_fotstada_aftan",
			"Klaufahalli":"nm_klaufahalli",
			"Júgurfesta":"nm_jugurfesta",
			"Júgurband":"nm_jugurband",
			"Júgurdýpt":"nm_jugurdypt",
			"Spenalengd":"nm_spenalengd",
			"Spenaþykkt":"nm_spenathykkt",
			"Spenastaða":"nm_spenastada",
			"Mjaltir":"nm_mjaltir",
			"Skap":"nm_skap",
			"Mjaltaröð":"mjaltarod",
			"Gæðaröð":"gaedarod"
		},
		"KM":{
			"Mjólkurmagn":"mjolkurmagn",
			"Fitumagn":"fitumagn",
			"Próteinmagn":"proteinmagn",
			"Fitu hlutfall":"fituhlutfall",
			"Prótein hlutfall":"proteinhlutfall",
			"Eigin afurðir":"eigin_afurdir",
			"Afurðamat":"afurdamat",
			"Frjósemi":"frjosemi",
			"Frumutala":"frumur",
			"Skrokkur":"skrokkur",
			"Júgur":"jugur",
			"Spenar":"spenar",
			"Mjaltir":"mjaltir",
			"Skap":"skap",
			"Ending":"ending",
			"Heildareinkunn":"heildareinkunn"
		},
		"DF":{
			"faedingarar":"faedingarar",
		    "kyn":"kyn",
		    "bu":"bu",
		    "busnumer":"busnumer",
		    "gripanumer":"gripanumer",
		    "einstaklingsnumer":"einstaklingsnumer",
		    "gripur_numer":"gripur_numer",
		    "fj_daetra_afurdir":"fj_daetra_afurdir",
		    "oryggi_afurdir":"oryggi_afurdir",
		    "fj_daetra_frumutala":"fj_daetra_frumutala",
		    "oryggi_frumutala":"oryggi_frumutala",
		    "fj_daetra_em":"fj_daetra_em",
		    "oryggi_em":"oryggi_em",
		    "fj_daetra_nm":"fj_daetra_nm",
		    "oryggi_nm":"oryggi_nm",
		    "fj_daetra_mjaltarod":"fj_daetra_mjaltarod",
		    "oryggi_mjaltarod":"oryggi_mjaltarod",
		    "fj_fargadra_daetra":"fj_fargadra_daetra",
		    "oryggi_ending":"oryggi_ending",
		    "nautanumer":"nautanumer",
		    "skrasetjari":"skrasetjari",
		    "skradags":"skradags",
		    "manudur":"manudur",
		    "ar":"ar",
		    "fjoldi_daetra":"fjoldi_daetra"
		}
	};
};